<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-01T19:13:13 NZST" name="Xero" finished-at="2021-09-01T19:13:35 NZST" duration-ms="21519">
    <groups>
    </groups>
    <test started-at="2021-09-01T19:13:13 NZST" name="Xero Login" finished-at="2021-09-01T19:13:35 NZST" duration-ms="21519">
      <class name="com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount@149e0f5d]" started-at="2021-09-01T19:13:13 NZST" name="setUp" finished-at="2021-09-01T19:13:13 NZST" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="startApp()[pri:0, instance:com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount@149e0f5d]" started-at="2021-09-01T19:13:13 NZST" name="startApp" finished-at="2021-09-01T19:13:16 NZST" duration-ms="2840" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="loginToAccount()[pri:0, instance:com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount@149e0f5d]" started-at="2021-09-01T19:13:16 NZST" name="loginToAccount" finished-at="2021-09-01T19:13:31 NZST" duration-ms="14818" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAccount -->
        <test-method is-config="true" signature="QuitAppMethod(org.testng.ITestResult)[pri:0, instance:com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount@149e0f5d]" started-at="2021-09-01T19:13:31 NZST" name="QuitAppMethod" finished-at="2021-09-01T19:13:32 NZST" duration-ms="667" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToAccount status=SUCCESS method=LogintoXeroValidAccount.loginToAccount()[pri:0, instance:com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount@149e0f5d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitAppMethod -->
        <test-method is-config="true" signature="QuitApp()[pri:0, instance:com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount@149e0f5d]" started-at="2021-09-01T19:13:35 NZST" name="QuitApp" finished-at="2021-09-01T19:13:35 NZST" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitApp -->
      </class> <!-- com.xeroFrameworkNikhat.testcases.LogintoXeroValidAccount -->
      <class name="com.xeroFrameworkNikhat.testcases.HomePageXero">
        <test-method is-config="true" signature="startApp()[pri:0, instance:com.xeroFrameworkNikhat.testcases.HomePageXero@1b1473ab]" started-at="2021-09-01T19:13:32 NZST" name="startApp" finished-at="2021-09-01T19:13:34 NZST" duration-ms="2733" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="logIn()[pri:0, instance:com.xeroFrameworkNikhat.testcases.HomePageXero@1b1473ab]" started-at="2021-09-01T19:13:34 NZST" name="logIn" finished-at="2021-09-01T19:13:34 NZST" duration-ms="1" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.xeroFrameworkNikhat.testcases.HomePageXero.logIn(HomePageXero.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method is-config="true" signature="QuitAppMethod(org.testng.ITestResult)[pri:0, instance:com.xeroFrameworkNikhat.testcases.HomePageXero@1b1473ab]" started-at="2021-09-01T19:13:34 NZST" name="QuitAppMethod" finished-at="2021-09-01T19:13:35 NZST" duration-ms="432" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logIn status=FAILURE method=HomePageXero.logIn()[pri:0, instance:com.xeroFrameworkNikhat.testcases.HomePageXero@1b1473ab] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.xeroFrameworkNikhat.testcases.BaseTest.QuitAppMethod(BaseTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitAppMethod -->
      </class> <!-- com.xeroFrameworkNikhat.testcases.HomePageXero -->
    </test> <!-- Xero Login -->
  </suite> <!-- Xero -->
</testng-results>
